"use client";

import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet";
import { Textarea } from "@/components/ui/textarea";
import type { Node } from "reactflow";

type NodeData = {
  label?: string;
  level?: string;
  description?: string;
  descriptionSource?: "pdf" | "ai";
  notes?: string;
};

type Props = {
  selectedNode: Node<NodeData> | null;
  onClose: () => void;
  onNotesChange: (notes: string) => void;
};

export default function InspectorPanel({ selectedNode, onClose, onNotesChange }: Props) {
  const label = selectedNode?.data?.label || "Node Details";
  const level = selectedNode?.data?.level || "concept";
  const description = (selectedNode?.data?.description || "").trim();
  const descriptionSource = selectedNode?.data?.descriptionSource === "pdf" ? "pdf" : "ai";
  const notes = selectedNode?.data?.notes ?? "";

  return (
    <Sheet open={!!selectedNode} onOpenChange={(open) => !open && onClose()}>
      <SheetContent>
        <SheetHeader className="gap-2">
          <div className="flex items-start justify-between gap-3">
            <SheetTitle className="break-words">{label}</SheetTitle>
            <span className="shrink-0 rounded-full border bg-muted px-2 py-0.5 text-xs font-medium text-muted-foreground">
              {level}
            </span>
          </div>
        </SheetHeader>

        <div className="mt-6 space-y-6">
          <section className="space-y-2">
            <div className="flex items-center justify-between gap-3">
              <div className="text-sm font-semibold text-foreground">AI Definition</div>
              <span className="shrink-0 rounded-full border bg-muted px-2 py-0.5 text-xs font-medium text-muted-foreground">
                {descriptionSource === "pdf" ? "content from PDF" : "content generated by AI"}
              </span>
            </div>
            {description ? (
              <div className="text-sm leading-relaxed text-foreground">{description}</div>
            ) : (
              <div className="text-sm text-muted-foreground">暂无 AI 定义</div>
            )}
          </section>

          <section className="space-y-2">
            <div className="text-sm font-semibold text-foreground">User Notes</div>
            <Textarea
              placeholder="Write your notes here..."
              className="min-h-[200px]"
              value={notes}
              onChange={(e) => onNotesChange(e.target.value)}
            />
          </section>
        </div>
      </SheetContent>
    </Sheet>
  );
}
